In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("ENB2012_data.csv")
df.head(100)

X1     X2     X3      X4   X5   X6   X7   X8     Y2  Unnamed: 9  \
0   0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  21.33         NaN   
1   0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  21.33         NaN   
2   0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  21.33         NaN   
3   0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  21.33         NaN   
4   0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  28.28         NaN   
..   ...    ...    ...     ...  ...  ...  ...  ...    ...         ...   
95  0.62  808.5  367.5  220.50  3.5  5.0  0.1  1.0  14.27         NaN   
96  0.98  514.5  294.0  110.25  7.0  2.0  0.1  2.0  25.95         NaN   
97  0.98  514.5  294.0  110.25  7.0  3.0  0.1  2.0  25.63         NaN   
98  0.98  514.5  294.0  110.25  7.0  4.0  0.1  2.0  26.13         NaN   
99  0.98  514.5  294.0  110.25  7.0  5.0  0.1  2.0  25.89         NaN   

    Unnamed: 10  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
..          ...  
95          NaN  
96          NaN  
97          NaN  
98          NaN  
99          NaN  

[100 rows x 11 columns]

In [3]:
cols_to_use = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'Y2']
df = df[cols_to_use]
df.head()

X1     X2     X3      X4   X5   X6   X7   X8     Y2
0  0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  21.33
1  0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  21.33
2  0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  21.33
3  0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  21.33
4  0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  28.28

In [4]:
df.nunique()

X1     12
X2     12
X3      7
X4      4
X5      2
X6      4
X7      4
X8      6
Y2    636
dtype: int64

In [5]:
df.shape

(1296, 9)

In [6]:
df.isna().sum()

X1    528
X2    528
X3    528
X4    528
X5    528
X6    528
X7    528
X8    528
Y2    528
dtype: int64

In [7]:
cols_to_fill_zero = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'Y2']
df[cols_to_fill_zero] = df[cols_to_fill_zero].fillna(0)
df.isna().sum()

X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
X7    0
X8    0
Y2    0
dtype: int64

In [8]:
df.head()

X1     X2     X3      X4   X5   X6   X7   X8     Y2
0  0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  21.33
1  0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  21.33
2  0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  21.33
3  0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  21.33
4  0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  28.28

In [9]:

x=df.drop('Y2',axis=1)
x.shape

(1296, 8)

In [10]:
# Giving Target Values
y=df['Y2']
y.shape

(1296,)

In [11]:
#Training Data set

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x, y, test_size=0.30, random_state=0)

In [12]:
#KFold
from sklearn.model_selection import KFold
kfold_validation = KFold(n_splits=5)

#cross_val_score
from sklearn.model_selection import cross_val_score

#mean_squared_error
from sklearn.metrics import mean_squared_error
mse = mean_squared_error

In [13]:
#Lasso Regression model

from sklearn.linear_model import Lasso
lasso_reg = Lasso().fit(X_train, y_train)
results_lasso = cross_val_score(lasso_reg,x,y,cv=kfold_validation)


C:\Users\BENSON\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.725e+03, tolerance: 1.843e+01
  model = cd_fast.enet_coordinate_descent(
C:\Users\BENSON\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.709e+03, tolerance: 2.158e+01
  model = cd_fast.enet_coordinate_descent(
C:\Users\BENSON\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the 

In [14]:
results_lasso

array([0.66485209, 0.84631103, 0.78887098, 0.        , 0.        ])

In [15]:
y_lasso_pred = lasso_reg.predict(X_test)

In [16]:
#Mean Square Error

print('mse',mean_squared_error(y_test, y_lasso_pred))

mse 7.896801583149152


In [17]:
#Ridge Regression model

from sklearn.linear_model import Ridge
ridge_reg = Ridge().fit(X_train, y_train)
results_ridge = cross_val_score(ridge_reg,x,y,cv=kfold_validation)

In [18]:
results_ridge

array([0.79795875, 0.89168793, 0.91314403, 0.        , 0.        ])

In [19]:
y_ridge_pred = ridge_reg.predict(X_test)

In [20]:
# Mean Square Error

print('mse',mean_squared_error(y_test, y_ridge_pred))

mse 5.413181921932733


In [21]:
#Elastic Net Regression model

from sklearn.linear_model import ElasticNet
eNet_reg = ElasticNet().fit(X_train, y_train)
results_eNet =cross_val_score(eNet_reg,x,y,cv=kfold_validation)


C:\Users\BENSON\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.912e+03, tolerance: 1.843e+01
  model = cd_fast.enet_coordinate_descent(
C:\Users\BENSON\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.812e+03, tolerance: 2.158e+01
  model = cd_fast.enet_coordinate_descent(
C:\Users\BENSON\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the 

In [22]:
results_eNet

array([0.64893004, 0.81044341, 0.76331306, 0.        , 0.        ])

In [23]:
y_eNet_pred=eNet_reg.predict(X_test)

In [24]:
#Mean Square Error

print('mse',mean_squared_error(y_test, y_eNet_pred))

mse 8.981930922548438
